const CONFIG={officialLineUrl:"https://lin.ee/u1LZ3VU",prices:{karma:0,creditor:0,ancestor:0,lineage:0,rice:0,offering:0},units:{karma:"位",creditor:"位",ancestor:"份",lineage:"份",rice:"包",offering:"桌"}};
const ITEMS=[{id:"karma",name:"因果普渡",subtitle:"可新增多位祈福對象",type:"person"},{id:"creditor",name:"冤親債主",subtitle:"可新增多位辦理對象",type:"person"},{id:"ancestor",name:"超薦祖先",subtitle:"可新增多位祖先或往生親友",type:"ancestor"},{id:"lineage",name:"九玄七祖",subtitle:"可新增多個家族資料",type:"lineage"},{id:"rice",name:"平安米",subtitle:"依包數登記",type:"quantity"},{id:"offering",name:"贊普",subtitle:"依桌數登記",type:"quantity"},{id:"donation",name:"自由贊助",subtitle:"金額自由填寫",type:"donation"}];
const blank=t=>t==="person"?{name:"",birth:"",calendar:"國曆",note:""}:t==="ancestor"?{surname:"",hall:"",deceased:"",relation:"",deathDate:"",note:""}:{surname:"",hall:"",title:"歷代祖先",note:""};
const state=Object.fromEntries(ITEMS.map(i=>[i.id,{selected:false,entries:["person","ancestor","lineage"].includes(i.type)?[blank(i.type)]:[],quantity:i.type==="quantity"?1:0,amount:0}]));
const selector=document.querySelector("#itemSelector"),dynamic=document.querySelector("#dynamicSections"),toast=document.querySelector("#toast"),modal=document.querySelector("#previewModal"),preview=document.querySelector("#previewText");
const money=v=>`NT$${Number(v||0).toLocaleString("zh-TW")}`;
function say(t){toast.textContent=t;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2000)}
function renderSelector(){selector.innerHTML=ITEMS.map(i=>`<label class="item-check ${state[i.id].selected?"active":""}"><input type="checkbox" data-select="${i.id}" ${state[i.id].selected?"checked":""}><span><strong>${i.name}</strong><small>${i.subtitle}</small></span></label>`).join("")}
function f(label,key,val,ph,hint,req=true){return `<label class="field"><span>${label}${req?' <b>*</b>':'（選填）'}</span><input data-key="${key}" value="${val||""}" placeholder="${ph}" ${req?"data-required='true'":""}><small>${hint}</small></label>`}
function card(item,d,n){let h=`<article class="entry-card" data-entry="${n}"><div class="entry-head"><strong>${item.type==="person"?"對象":item.type==="ancestor"?"祖先／往生親友":"家族資料"} ${n+1}</strong>${state[item.id].entries.length>1?`<button type="button" class="remove-btn" data-remove="${n}">刪除</button>`:""}</div><div class="field-grid">`;
if(item.type==="person")h+=f("祈福姓名","name",d.name,"例如：王大明","請填實際接受科儀的人，可填本人、家人或親友。")+f("出生日期","birth",d.birth,"例如：82/08/22","請填此位對象的出生日期。")+`<label class="field"><span>曆別 <b>*</b></span><select data-key="calendar"><option ${d.calendar==="國曆"?"selected":""}>國曆</option><option ${d.calendar==="農曆"?"selected":""}>農曆</option></select><small>請依照出生日期選擇國曆或農曆。</small></label>`+f("個別備註","note",d.note,"例如：本人、父親","可補充此人與聯絡人的關係。",false);
if(item.type==="ancestor")h+=f("祖先姓氏","surname",d.surname,"例如：王","請填欲超薦祖先或往生親友的姓氏。")+f("堂號","hall",d.hall,"例如：太原堂","不知道可留空。",false)+f("往生者姓名","deceased",d.deceased,"例如：王○○","請填祖先或往生親友姓名；歷代祖先可直接填寫。")+f("與聯絡人關係","relation",d.relation,"例如：祖父、祖母","請填往生者與聯絡人的關係。")+f("往生日期","deathDate",d.deathDate,"例如：民國95年或不詳","不清楚可留空。",false)+f("個別備註","note",d.note,"例如：歷代祖先","可補充其他內容。",false);
if(item.type==="lineage")h+=f("家族姓氏","surname",d.surname,"例如：王","請填要登記九玄七祖的家族姓氏。")+f("堂號","hall",d.hall,"例如：太原堂","不知道可留空。",false)+f("登記名稱","title",d.title,"例如：歷代祖先","一般可填九玄七祖或歷代祖先。")+f("備註","note",d.note,"例如：王氏歷代祖先","可補充其他家族需求。",false);
return h+"</div></article>"}
function renderDynamic(){dynamic.innerHTML=ITEMS.filter(i=>state[i.id].selected).map(i=>{let b="";if(["person","ancestor","lineage"].includes(i.type))b=`<div class="entries">${state[i.id].entries.map((d,n)=>card(i,d,n)).join("")}</div><button type="button" class="add-btn" data-add>＋ 新增一筆</button>`;if(i.type==="quantity")b=`<div class="entries"><div class="quantity-row"><div><strong>${i.name}數量</strong><div class="field-note">請選擇${CONFIG.units[i.id]}數。</div></div><button type="button" class="qty-btn" data-qty="-1">−</button><input class="qty-value" type="number" min="1" value="${state[i.id].quantity}" data-quantity><button type="button" class="qty-btn" data-qty="1">＋</button></div></div>`;if(i.type==="donation")b=`<div class="entries"><label class="field"><span>自由贊助金額（選填）</span><input type="number" min="0" value="${state[i.id].amount||""}" data-donation placeholder="例如：500"><small>請直接填寫金額。</small></label></div>`;return `<section class="dynamic-section" data-section="${i.id}"><div class="dynamic-title"><h3>${i.name}</h3><p>${i.subtitle}</p></div>${b}</section>`}).join("");summary()}
function total(){return ITEMS.reduce((s,i)=>{if(!state[i.id].selected)return s;if(["person","ancestor","lineage"].includes(i.type))return s+CONFIG.prices[i.id]*state[i.id].entries.length;if(i.type==="quantity")return s+CONFIG.prices[i.id]*state[i.id].quantity;if(i.type==="donation")return s+Number(state[i.id].amount||0);return s},0)}
function summary(){document.querySelector("#selectedCount").textContent=`${ITEMS.filter(i=>state[i.id].selected).length} 項`;document.querySelector("#grandTotal").textContent=money(total())}
selector.onchange=e=>{let id=e.target.dataset.select;if(!id)return;state[id].selected=e.target.checked;renderSelector();renderDynamic()}
dynamic.onclick=e=>{let s=e.target.closest("[data-section]");if(!s)return;let id=s.dataset.section,item=ITEMS.find(x=>x.id===id);if(e.target.matches("[data-add]")){state[id].entries.push(blank(item.type));renderDynamic()}if(e.target.matches("[data-remove]")){state[id].entries.splice(+e.target.dataset.remove,1);renderDynamic()}if(e.target.matches("[data-qty]")){state[id].quantity=Math.max(1,state[id].quantity+(+e.target.dataset.qty));renderDynamic()}}
dynamic.oninput=e=>{let s=e.target.closest("[data-section]");if(!s)return;let id=s.dataset.section,en=e.target.closest("[data-entry]");if(en&&e.target.dataset.key)state[id].entries[+en.dataset.entry][e.target.dataset.key]=e.target.value;if(e.target.matches("[data-quantity]"))state[id].quantity=Math.max(1,+e.target.value||1);if(e.target.matches("[data-donation]"))state[id].amount=+e.target.value||0;summary()}
function validate(){document.querySelectorAll(".invalid").forEach(x=>x.classList.remove("invalid"));let bad=[];["contactName","contactPhone"].forEach(id=>{let x=document.querySelector("#"+id);if(!x.value.trim()){x.classList.add("invalid");bad.push(1)}});if(!ITEMS.some(i=>state[i.id].selected)){say("請至少選擇一個報名項目");return false}document.querySelectorAll("[data-required='true']").forEach(x=>{if(!x.value.trim()){x.classList.add("invalid");bad.push(1)}});if(bad.length){say("請完成必填資料");document.querySelector(".invalid")?.scrollIntoView({behavior:"smooth",block:"center"});return false}return true}
function build(){let l=["🏮 混元九龍殿 中元普渡報名","","━━━━━━━━━━━━━━","【聯絡人資料】",`報名類型：${document.querySelector("#registrationType").value}`,`姓名：${document.querySelector("#contactName").value}`,`電話：${document.querySelector("#contactPhone").value}`,`LINE 名稱：${document.querySelector("#lineName").value||"未填寫"}`,"━━━━━━━━━━━━━━"];ITEMS.filter(i=>state[i.id].selected).forEach(i=>{l.push("",`【${i.name}】`);if(i.type==="person"){l.push(`共 ${state[i.id].entries.length} 位`);state[i.id].entries.forEach((d,n)=>l.push("",`${n+1}. ${d.name}`,`出生日期：${d.birth}（${d.calendar}）`,`備註：${d.note||"無"}`))}if(i.type==="ancestor"){l.push(`共 ${state[i.id].entries.length} 筆`);state[i.id].entries.forEach((d,n)=>l.push("",`${n+1}. ${d.deceased}`,`祖先姓氏：${d.surname}`,`堂號：${d.hall||"不詳／未填"}`,`關係：${d.relation}`,`往生日期：${d.deathDate||"不詳／未填"}`,`備註：${d.note||"無"}`))}if(i.type==="lineage"){l.push(`共 ${state[i.id].entries.length} 筆家族資料`);state[i.id].entries.forEach((d,n)=>l.push("",`${n+1}. ${d.surname}氏 ${d.title}`,`堂號：${d.hall||"不詳／未填"}`,`備註：${d.note||"無"}`))}if(i.type==="quantity")l.push(`數量：${state[i.id].quantity} ${CONFIG.units[i.id]}`);if(i.type==="donation")l.push(`金額：${money(state[i.id].amount)}`);l.push("","──────────────────")});l.push("","【費用明細】");ITEMS.filter(i=>state[i.id].selected).forEach(i=>{let q=["person","ancestor","lineage"].includes(i.type)?state[i.id].entries.length:i.type==="quantity"?state[i.id].quantity:1;if(i.type==="donation")l.push(`${i.name}：${money(state[i.id].amount)}`);else l.push(`${i.name}：${q} ${CONFIG.units[i.id]} × ${CONFIG.prices[i.id]?money(CONFIG.prices[i.id]):"金額請廟方確認"}`)});l.push("",`預估總金額：${money(total())}`,"※ 實際費用與登記方式以廟方最後確認為準。","","━━━━━━━━━━━━━━","【其他備註】",document.querySelector("#generalNote").value||"無","━━━━━━━━━━━━━━");return l.join("\n")}
async function copy(t){try{await navigator.clipboard.writeText(t)}catch{let a=document.createElement("textarea");a.value=t;document.body.appendChild(a);a.select();document.execCommand("copy");a.remove()}say("報名內容已複製")}
document.querySelector("#previewBtn").onclick=()=>{if(!validate())return;preview.textContent=build();modal.hidden=false;document.body.style.overflow="hidden"}
document.querySelectorAll("[data-close]").forEach(x=>x.onclick=()=>{modal.hidden=true;document.body.style.overflow=""})
document.querySelector("#copyFromPreview").onclick=()=>copy(preview.textContent)
document.querySelector("#registrationForm").onsubmit=async e=>{e.preventDefault();if(!validate())return;await copy(build());setTimeout(()=>window.open(CONFIG.officialLineUrl,"_blank","noopener"),400)}
renderSelector();renderDynamic();
